### ISSUE TITLE
[Users] Request / Input Validation

### ISSUE THREAD

**Issue by dev4ult** [Capstone-Alterra/go-raih-peduli#137]
fullname , email, address, no hp, gender, password termasuk required field
email : harus ada (@) nya
no hp : minimal 10 digit
password : minimal 8 karakter
fullname : tidak boleh diisi simbol

**Comment by IrvanWijayaSardam** [comment]
issues fix at this commit

https://github.com/Capstone-Alterra/go-raih-peduli/commit/e0a239b58eb408d63a9e9dfb5ad7e8423baf8b5a
