### ISSUE TITLE
[Fundraises] Search Fundraises

### ISSUE THREAD

**Issue by Golfantara** [Capstone-Alterra/go-raih-peduli#16]
[Optional] Try to implement Elastic Search

**Comment by dev4ult** [comment]
Success get all fundraises with page and size as the pagination query param. Also title for the search key
- controller : GetFundraises
- service : FindAll
- repository : Paginate

not yet : add pagination as a response

**Comment by dev4ult** [comment]
pagination as response is not required proposed by mentor
